name: Build and publish Onbox packages

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

env:
  solution: Onbox.sln
  solutionFilter: OnboxNuget.slnf
  analyzers: analyzers/Onbox.Analyzers.Build.sln
  buildPlatform: x64
  buildConfiguration: R2019
  newNamespace: V9
  newVersion: 0.9.0.1

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2

      - uses: microsoft/setup-msbuild@v1.0.2

      - name: Versioning
        run: .\ren.ps1 -oldNs .VDev -newNs ${{ env.newNamespace }} -oldV 0.99.99.99 -newV ${{ env.newVersion }}
        shell: powershell

      - name: Nuget Install
        uses: nuget/setup-nuget@v1

      - name: Nuget Restore Build Projects
        run: nuget restore ${{ env.solution }}

      - name: Visual Studio 2019 Build Projects
        run: msbuild '${{ env.solutionFilter }}' /p:configuration='${{ env.buildConfiguration }}' /p:platform='${{ env.buildPlatform }}'

      - name: Package NuGet with symbols
        run: |
          # Navigate to the directory containing .nuspec files
          cd build
          # Loop through all .nuspec files in the directory and pack them with symbols
          foreach ($file in Get-ChildItem -Path *.nuspec)
          {
            nuget pack $file.Name -Symbols -SymbolPackageFormat snupkg
          }
        shell: powershell

      - name: Copy Nuget to Staging Artifacts
        run: Copy-Item 'build//*.nupkg' '${{ github.workspace }}'
        shell: powershell

      - name: Nuget Restore Analyzers
        run: nuget restore ${{ env.analyzers }}
        shell: powershell

      - name: Visual Studio 2019 Build Analyzers
        run: msbuild '${{ env.analyzers }}' /p:configuration='Release' /p:platform='Any CPU'

      - name: Copy Analyzers Nuget to Staging Artifacts
        run: Copy 'analyzers/Onbox.Analyzers/Onbox.Analyzers.Package/bin/Release//*.nupkg' '${{ github.workspace }}'

      - name: Artifacts Publish
        uses: actions/upload-artifact@v2
        with:
          path: ${{ github.workspace }}
          name: packages
